[profile.default]
src = "src"
out = "out"
libs = ["lib"]


remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]


[rpc_endpoints]
sei_testnet = "https://evm-rpc-testnet.sei-apis.com"
sei_mainnet = "https://evm-rpc.sei-apis.com"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
